Name:           ros-jade-nao-dashboard
Version:        0.1.2
Release:        0%{?dist}
Summary:        ROS nao_dashboard package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/nao_dashboard
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-diagnostic-aggregator
Requires:       ros-jade-diagnostic-msgs
Requires:       ros-jade-naoqi-msgs
Requires:       ros-jade-rqt-robot-dashboard
Requires:       ros-jade-rqt-robot-monitor
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-diagnostic-aggregator
BuildRequires:  ros-jade-diagnostic-msgs
BuildRequires:  ros-jade-naoqi-msgs
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-rqt-robot-monitor

%description
nao_dashboard is a GUI for monitoring the state of a Nao robot. It is a port of
pr2_dashboard and shows status information like battery status, joint
temperatures, and joint stiffness, as well as integrating ROS tools like
rxconsole and robot_monitor.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri May 01 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.1.2-0
- Autogenerated by Bloom

